name = "loan-guide"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd apps/web && npm install && npm run build"

[build.upload]
format = "directory"

# Pages specific configuration
pages_build_output_dir = "apps/web/dist"
